-- DEPRECATED: do not run this file.
--
-- The previous version granted public access to sensitive records. Use
-- security-hardening.sql instead. It replaces legacy policies with role-based
-- Row Level Security and is safe to run on the current application schema.
